name: Copy files and Start Nodemon Service

on:
  push:
    branches:
      - binge-movies

jobs:
  copy-files-to-server:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create Dir bingeplus
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            sudo mkdir -p /var/www/html/bingeplus-movies
            sudo chown -R binge+:binge+ /var/www/html/bingeplus-movies

      - name: Copy files to GCP VM
        uses: appleboy/scp-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          source: "."
          target: "/var/www/html/bingeplus-movies"  # Target directory on GCP VM

  start_nodemon:
    runs-on: ubuntu-latest
    needs: copy-files-to-server  # Ensures this job runs after the 'deploy' job

    steps:
      - name: Start Nodemon
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            cd /var/www/html/bingeplus-movies/server
            chmod +x start_nodemon.sh
            ./start_nodemon.sh  # Start the nodemon in Background

      - name: Restart Apache2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2

  # Start Nodemon Service for github-actions-dashboard
  start_nodemon-2: 
    runs-on: ubuntu-latest
    needs: start_nodemon  

    steps:
      - name: Start Nodemon
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            cd /var/www/html/bingeplus-movies/github-actions-dashboard
            chmod +x start_nodemon_workflow_monitoring_dashboard.sh
            ./start_nodemon_workflow_monitoring_dashboard.sh  

      - name: Restart Apache2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.GCP_VM_HOST }}
          username: ${{ secrets.GCP_VM_USERNAME }}
          key: ${{ secrets.GCP_VM_PRIVATE_KEY }}
          script: |
            sudo systemctl restart apache2 
