name: Build and Push Docker Image To Docker Hub and Artifact Registry
on:
  push:
    branches:
      - binge-movies

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    strategy:
      matrix:
        image_name: ["binge-plus-movies"] # Define multiple image names if needed

    steps:
      - name: Checkout code
        uses: actions/checkout@9bb56186c3b09b4f86b1c65136769dd318469633 # v4.1.2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          registry: docker.io # Optional, good practice to be explicit
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest .

      - name: Push Docker image to Docker Hub
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ matrix.image_name }}:latest

      - name: Google Cloud Auth
        uses: 'google-github-actions/auth@v2'
        with:
          credentials_json: ${{ secrets.GCP_CREDENTIALS }} 

      - name: Configure Docker Auth
        run: |
          gcloud auth configure-docker us-central1-docker.pkg.dev

      - name: Build Docker Image
        run: |
          docker build -t us-central1-docker.pkg.dev/binge-plus-deployment/binge-plus-registry/binge-plus-movies:${{ github.sha }} .

      - name: Push to Artifact Registry
        run: |
          docker push us-central1-docker.pkg.dev/binge-plus-deployment/binge-plus-registry/binge-plus-movies:${{ github.sha }}
      
